### ISSUE TITLE
Add setting to determine panel position

### ISSUE THREAD

**Issue by halfmexican** [swsnr/gnome-shell-extension-xwayland-indicator#6]
It would be nice to determine where on the panel to place the indicator

**Comment by swsnr** [comment]
I have no need for this, and no time to implement it. You'll need to make a pull request to see it done, including a setting schema, etc.  See https://github.com/swsnr/gnome-shell-extension-utc-clock for how settings are done in one of my other extensions; a pull request here would have to do it the same way.

Meanwhile I'm closing this issue, simply because it's not actionable for myself.  A pull request would be welcome nonetheless.
